version: '3'
services:
  tiny:
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
